// Generated by CoffeeScript 1.10.0
(function() {
  var Validator, internals, root;

  Validator = require('./validator');

  internals = {
    baseUrl: 'http://localhost'
  };

  root = {};

  root.defaults = function(options) {
    return internals.baseUrl = options.baseUrl;
  };

  root.look = function(options, schemas, done) {
    var validator;
    options.baseUrl = options.baseUrl != null ? options.baseUrl : internals.baseUrl;
    validator = new Validator(options, schemas, done);
    return validator.run();
  };

  module.exports = root;

}).call(this);
