// Generated by CoffeeScript 1.10.0
(function() {
  var v_sight;

  v_sight = require('../index');

  v_sight().flush({
    bucket: 'bucketName',
    admin: 'administrator',
    password: 'admin'
  }, function(result) {
    return console.log(result);
  });

}).call(this);
